export enum TextLayer {
  largeBold5X = 'largeBold5X',
  largeMedium5X = 'largeMedium5X',
  largeRegular5X = 'largeRegular5X',
  largeBold4X = 'largeBold4X',
  largeMedium4X = 'largeMedium4X',
  largeRegular4X = 'largeRegular4X',
  largeBold3X = 'largeBold3X',
  largeMedium3X = 'largeMedium3X',
  largeRegular3X = 'largeRegular3X',
  largeBold2X = 'largeBold2X',
  largeMedium2X = 'largeMedium2X',
  largeRegular2X = 'largeRegular2X',
  largeBoldX = 'largeBoldX',
  largeMediumX = 'largeMediumX',
  largeRegularX = 'largeRegularX',
  largeBold = 'largeBold',
  largeRegular = 'largeRegular',

  mediumBold = 'mediumBold',
  mediumRegular = 'mediumRegular',
  regularBold = 'regularBold',
  baseBoldNormal = 'baseBoldNormal',
  baseRegularNormal = 'baseRegularNormal',
  baseLightNormal = 'baseLightNormal',
  smallBoldNormal = 'smallBoldNormal',
  smallRegularNormal = 'smallRegularNormal',
  smallLightNormal = 'smallLightNormal',

  smallBoldNormalX = 'smallBoldNormalX',
  smallRegularNormalX = 'smallRegularNormalX',
  smallLightNormalX = 'smallLightNormalX',
  smallBoldNormal2X = 'smallBoldNormal2X',
  smallRegularNormal2X = 'smallRegularNormal2X',
  smallLightNormal2X = 'smallLightNormal2X'
}
